//
//  Functions.swift
//  Quizzler
//
//  Created by Julian Silvestri on 2020-09-01.
//  Copyright © 2020 Julian Silvestri. All rights reserved.
//
import UIKit
import Foundation

///Filter out the quiz questions for the category that have less than 20 questions.
func filterQuizzes(){
    QuizCount.quizCount.removeAll(where: {$0.categoryQuestionCount.totalEasyQuestionCount < 20})
    QuizCount.quizCount.removeAll(where: {$0.categoryQuestionCount.totalMediumQuestionCount < 20})
    QuizCount.quizCount.removeAll(where: {$0.categoryQuestionCount.totalHardQuestionCount < 20})
}

func hexStringToUIColor (hex:String) -> UIColor {
    var cString:String = hex.trimmingCharacters(in: .whitespacesAndNewlines).uppercased()
    
    if (cString.hasPrefix("#")) {
        cString.remove(at: cString.startIndex)
    }
    
    if ((cString.count) != 6) {
        return UIColor.gray
    }
    
    var rgbValue:UInt64 = 0
    Scanner(string: cString).scanHexInt64(&rgbValue)
    
    return UIColor(
        red: CGFloat((rgbValue & 0xFF0000) >> 16) / 255.0,
        green: CGFloat((rgbValue & 0x00FF00) >> 8) / 255.0,
        blue: CGFloat(rgbValue & 0x0000FF) / 255.0,
        alpha: CGFloat(1.0)
    )
}

func alertActionBasic(viewController: UIViewController, title:String, message: String, completionHandler: @escaping(Bool?)->Void){
    let alertController = UIAlertController(title: title, message: message, preferredStyle: .alert)
    alertController.addAction(UIAlertAction(title: "Ok", style: .default, handler: {action in
        completionHandler(true)
    }))
    viewController.present(alertController, animated: true)
}
func alertActionYesNo(viewController: UIViewController, title:String, message: String, completionHandler: @escaping(Bool)->Void){
    let alertController = UIAlertController(title: title, message: message, preferredStyle: .alert)
    alertController.addAction(UIAlertAction(title: "Yes", style: .default, handler: {action in
        completionHandler(true)
    }))
    alertController.addAction(UIAlertAction(title: "No", style: .cancel, handler: {action in
        completionHandler(false)
    }))
    viewController.present(alertController, animated: true)
}

func alertActionYesNoWithImage(viewController: UIViewController, title:String, message: String, image: UIImage, completionHandler: @escaping(Bool)->Void){
    let alertController = UIAlertController(title: title, message: message, preferredStyle: .alert)
    alertController.addAction(UIAlertAction(title: "Next Question", style: .default, handler: {action in
        completionHandler(true)
    }))

    let imageView = UIImageView(frame: CGRect(x: 0, y: 100, width: 64, height: 64))
    imageView.image = image
    imageView.contentMode = .scaleAspectFit
    alertController.view.addSubview(imageView)

    imageView.translatesAutoresizingMaskIntoConstraints = false
    let height = NSLayoutConstraint(item: alertController.view as Any, attribute: .height, relatedBy: .equal, toItem: nil, attribute: .notAnAttribute, multiplier: 1, constant: 215)
    let width = NSLayoutConstraint(item: imageView, attribute: .width, relatedBy: .equal, toItem: nil, attribute: .notAnAttribute, multiplier: 1.0, constant: 64.0)
    let centerX = NSLayoutConstraint(item: imageView, attribute: .centerX, relatedBy: .equal, toItem: alertController.view, attribute: .centerX, multiplier: 1, constant: 0)
    let centerY = NSLayoutConstraint(item: imageView, attribute: .centerY, relatedBy: .equal, toItem: alertController.view, attribute: .centerY, multiplier: 1, constant: 0)
    alertController.view.addConstraint(height)
    alertController.view.addConstraint(width)
    alertController.view.addConstraint(centerX)
    alertController.view.addConstraint(centerY)

    viewController.present(alertController, animated: true)
}

func decode(str: String)->NSAttributedString{
    var textToDecode = NSAttributedString()
    if let data = str.data(using: .utf8) {
        do {
            let attrStr = try NSAttributedString(data: data, options: [.documentType: NSAttributedString.DocumentType.html], documentAttributes: nil)
//            print(attrStr)
            textToDecode = attrStr
        } catch {
            print(error)
        }
    }
    return textToDecode
}
func decodeArrayOfStrings(str: [String])->[NSAttributedString]{
    var textToDecode = [NSAttributedString]()
    
    for values in str {
        if let data = values.data(using: .utf8) {
            do {
                let attrStr = try NSAttributedString(data: data, options: [.documentType: NSAttributedString.DocumentType.html], documentAttributes: nil)
//                print(attrStr)
                textToDecode.append(attrStr)
            } catch {
                print(error)
            }
        }
    }
    return textToDecode
}


//func loadQuizzes() {
//    //MARK: General History 1
//    UserDefaults.setValue(0, forKey: "quiz_1_score")
//    Quizzes.quizzes.append(Quizzes(title: "General History 1", description: "From recent to long ago!",questions:[0:"In what year did Martin Luther King Jr. win the Nobel Peace price?", 1: "The 2016 Paris Agreement deal's primary global issue was about what?",2:"In what year did Christopher Columbus make his famous voyage to find to find a direct water route from Europe to Asia?",3:"American Patriots Dumped what into the Boston harbor in 1773 to protest British import tax?",4:"The first N.A.S.A Mars Rover was named what?",5:"Which Canadian province became the first to allow the testing of self-driving vehicles on public roads?",6:"What was the first U.S state to legalize same-sex marriage?",7:"In response to the Boston Tea Party, the British passes what Act?",8:"The 21'st president of the United States was?",9:"Disney theme park built its first theme park outside of the U.S in which country?",10:"When did the Mormons first settle in Utah?",11:"Ben Franklin used what two objects to prove lightning contains electricity?",12:"Who was the 17th Prime Minister of Canada?",13:"What was the name of the famous German Encryption device used in WWII",14:"Davy Crocket died in what famous battle?",15:"The first tank used in battle was used in what war?",16:"In what year was the famous voyage of the tragic Titanic?",17:"Samuel Adams led the famous patriot political party called?",18:"In 1988 Canada hosted what famous event?",19:"How long did Prohibiton last in the U.S?"], answer: [0:"1964",1:"Climate Change",2:"1492",3:"Tea",4:"Soujourner",5:"Ontario",6:"Massachusetts",7:"The Intolerable Acts",8:"Chester A. Arthuer",9:"Japan",10:"1847",11:"Kite & Key",12:"Joe Clark",13:"Engigma Machine",14:"The Alamo",15:"WWI",16:"1912",17:"The Boston Tea Party",18:"Winter Olympics",19:"13"], possibleAnswers: [0:["1960", "1975","1980"],1:["World Hunger","Depopulation","North Korea"], 2:["1480","1440","1501"],3:["Alcohol","Ammunition","Tobacco"],4:["Mars-1","Star Gazer","AL"],5:["B.C","P.E.I","Alberta"],6:["California","New York","Texas"],7:["The Lawless Act", "John Jones Act","The Rebel Act"],8:["John F. Kennedy", "Grover Cleavland","Donald Trump"],9:["U.K","France","Germany"],10:["1801","1701","1888"],11:["Bike & Golf Club","Battery & Pipe" ,"Fishing Rod & Key"],12:["Jean Cretiean","John Turner", "Arthur Meighen"],13:["Crypto-ZZ","Dorzer Machine","Enigmatic Machine"],14:["Baker Field","Quanton Road","The Battle of Midway"],15:["WWII","The Cold War","War of 1812"],16:["1910","1902","1899"],17:["The Black Panthers","The Republican Party","The Democratic Party"],18:["Summer Olympics","FIFA World Cup","Wimbeldon"],19:["5","19","9"]], imageName: ""))
//    //MARK: General History 2
//    Quizzes.quizzes.append(Quizzes(title: "General History 2", description: "General history questions. Some are easy, so are not.", questions: [0:"Which country was the first to recognize the Republic of Texas?",1:"Which colony was established by the passengers of the Mayflower?",2:"What was the famous forced march of the Cherokee from Georgia to Indian Country called?",3:"What ancient empire began as an alliance of three city-states?",4:"In 1940 in the state of Washington, the Tacoma Narrows Bridge collapsed. What was the cause? ",5:"Which fish, previously though to be extinct, was rediscovered in 1939?",6:"What Jelly Belly flavor was created for Ronald Reagan's inauguration?",7:"Who succeeded James Garfield as US president?",8:"Who were the first people in the world to eat popcorn?",9:"When was the tire company, Michelin, founded?",10:"Which developed nation had the highest unemployment rate in the 1920's?",11:"Where is the only royal palace in the United States?",12:"How many countries were part of the Soviet Union?",13:"Which country was the first European nation to reach Japan?",14:"Battle of Bull Run",15:"What was Hewlett-Packard's first successful product?",16:"What were southerners who cooperated with the North after the Civil War known as?",17:"In what year did Soviet Russia finally declare war on Japan?",18:"Who nicknamed New York City 'Gotham'?",19:"What war ended with the Treaty of Ghent?"], answer: [0:"France",1:"Plymouth Colony",2:"The Trail of Tears",3:"The Aztec Empire",4:"High Winds",5:"The Coelacanth",6:"Blueberry",7:"Chester A. Arthur",8:"The Natives in the Americas",9:"1889",10:"Germany",11:"Hawaii",12:"15",13:"Portugal",14:"Battle of Bull Run",15:"An audio oscillator",16:"Scalawag",17:"1945",18:"Washington Irving",19:"War of 1812"], possibleAnswers: [0:["Britain","Germany","Canada"],1:["New Jersey Colony","Summsville colony","New York"],2:["The Bloody March","The March of Sorrow","The Path of Sinners"],3:["The Myan Empire","The Inca Empire","The Olmec Empire"],4:["A bomb","An earthquake","Structural Failure"],5:["The platypus","Toothcarps","The Houting fish"],6:["Orange","Cranberry","Peach"],7:["Rutheford B. Hayes","Ulysses S. Grant","Grover Cleavland"],8:["Americans","Canadians","Mexicans"],9:["1900","1901","1922"],10:["Britain","France","United States"],11:["Washington","Texas","New Mexico"],12:["1","10","20"],13:["Poland","Russia","Britain"],14:["Battle of Appomattox Court House","Battle of Fort Donelson","Battle of Stones River"],15:["Tape Recorder","Ink Jet Printer","The first computer motherboard"],16:["Traitors","Nothingers","Scamps"],17:["1944","1943","1946"],18:["Nathaniel Hawthorne","Herman Melville","Bruce Banner"],19:["American Civil War","WWI","Korean War"]], imageName: ""))
//    //MARK: The Black Death -- INCOMPLETE
//    //Quizzes.quizzes.append(Quizzes(title: "The Black Death", description: "What do you know about the Black Death? Take this quiz and find out.", questions: [0:"What is a symptom of the Black Death?",1:"What was the main period the Black Death affected Europe?",2:"How long does an infected person generally last before becoming ill?",3:"How did the plague make its way into Europe?",4:"What is the estimated death count from the Black Death?",5:"What continent is it believed the Black Death Originated from?",6:"The most dangerous type of Black Death is what?",7:"What Italian city is said to be ground zero for the outbreak in Europe?",8:"What is a common name for the Black Death?",9:"",10:"",11:"",12:"",13:"",14:"",15:"",16:"",17:"",18:"",19:""], answer: [0:"Swellings in the groin, armpits and neck",1:"1300's",2:"3-5 days",3:"Rats Carrying Fleas",4:"25 million",5:"Asia",6:"Septicemic",7:"Sicily",8:"The Bubonic Plague",9:"",10:"",11:"",12:"",13:"",14:"",15:"",16:"",17:"",18:"",19:""], possibleAnswers: [0:["Blindeness","Mania","Loss of smell"],1:["1100's","1500's","1600's"],2:["1-2 days","10 days","2 weeks"],3:["Birds","Person to person","Rotting meats"],4:["100 million", "10 million","15 million"],5:["North America","South America","Australia"],6:["Pneumonic","Respiratory","Viral"],7:["Rome","Venice","Florence"],8:["Black Disease","Eternal Sleep","The Spots"],9:[""],10:[""],11:[""],12:[""],13:[""],14:[""],15:[""],16:[""],17:[""],18:[""],19:[""]], imageName: ""))
//    //MARK: General Knowledge 1
//    Quizzes.quizzes.append(Quizzes(title: "General Knowledge", description: "Whoever said knowing useless facts will never come in handy is about to eat their words!", questions: [0:"The famous Atari video game 'Missile Command', came out in what year?",1:"In what year did Starbucks open their very first store?",2:"The letter 'P' in NATO phonetic alphabet stands for what?",3:"Which of the following color's is not inside a standard bag of M&M's?",4:"Who was The Unabomber?",5:"In a video game the term N.P.C means what?",6:"The practice of a woman taking more than one husband is called what?",7:"The first Latino Baseball Player inducted into the Baseball Hall of Fame in 1973 was?",8:"What university is home to the Fighting Irish?",9:"How many rings are on the Olympic flag?",10:"What plant do people traditionally kiss underneath?",11:"In health terminology, what does the acrynonm B.M.I stand for?",12:"Surfers and skaters who use their left food on the back of the board is referred to as?",13:"Someone who becomes canonized means what?",14:"The phrase 'Rolling out the red carpet', originates from what country?",15:"What fish requires a special license in order to be able to prepare in Japan?",16:"A Stinger cocktail contains Cognac and what?",17:"To bowl a perfect game (Bowling), a player needs how many strikes?",18:"In a game of Pool, what color is the 6-ball?",19:"The Dewey Decimal System categorizes what in the 800's?"], answer: [0:"1980",1:"1971",2:"Papa",3:"Purple",4:"Theodore Kaczynski",5:"Non-Player Character",6:"Polyandry",7:"Roberto Clemente",8:"Notre Dame",9:"5",10:"Misletoe",11:"Body Mass Index",12:"Goofy",13:"A Saint",14:"Greece",15:"Blowfish(Fugu)",16:"Creme de menthe",17:"12",18:"Green",19:"Literature"], possibleAnswers: [0:["1978","1989","1960"],1:["1999","2000","1974"],2:["Peter","Paulie","Pronto"],3:["Green","Brown","Blue"],4:["Peter Maddrigal","Anthony Persium","Piotr Zajac"],5:["Not Perfect Constantly","Never Perform Cheaply"],6:["Polygamy","Polygyny","Polygamous"],7:["Juan Diego","Alex Rodriquez","Jose Gomez"],8:["Ohio State","Georgia Tech","Central Michigan"],9:["4","6","7"],10:["Roses","Basil","Floxglove"],11:["Big Moving Legs","Biological Mitigated Injury","Body Maintenance Inclusive"],12:["Lefty","Derpy","Retro"],13:["Deceased","Sworn to Royalty","Imprisoned"],14:["U.S.A","France","Italy"],15:["Tuna","Shark","Eel"],16:["Vodka","Tequila","Triple Sec"],17:["14","10","18"],18:["Yellow","Orange","Purple"],19:["History","Science","Philosophy"]], imageName: ""))
//    //MARK: General Knowledge 2
//    Quizzes.quizzes.append(Quizzes(title: "General Knowledge 2", description: "Whoever said knowing useless facts will never come in handy is about to eat their words!", questions: [0:"In which country was the International Red Cross founded?",1:"The term Xenogolossophobia means what?",2:"In 1935 Mickey Mouse became the first cartoon character to be licensed to be placed on what object?",3:"A Diamond is the birthstone of which month?",4:"The 'Curse of the Bambino' affected which baseball team?",5:"Neopolitan ice cream contains what three flavors?",6:"Witches gathered in groups of 13, these are known as what?",7:"The famous sword in King Arthurs is called what?",8:"A female turkey is called what?",9:"The soft drink Mountain Dew, is aslso a euphemism for what?",10:"Which country gifted The Statue of Liberty to the U.S.A?",11:"Which computer programming language is also another word for coffee?",12:"A Brannock device is used when shipping for what product?",13:"A Rueben sandwhich traditionally uses what meat?",14:"The White House contains how many rooms?",15:"The Taj Mahal is also known as what?",16:"Ireland was teh first European country to ban what inside of bars?",17:"Which color is always on top of a Rainbow?",18:"The Chinese calendar contains one year dedicated to a bird, which bird is it?",19:"Sub-Zero is a character in what video game?"], answer: [0:"Switzerland",1:"The fear of learning or using foreign languages",2:"A lunch box",3:"April",4:"Boston Red Sox",5:"Vanilla, Chocolate, Strawberry",6:"Covens",7:"Excalibur",8:"Hen",9:"Moonshine",10:"France",11:"Java",12:"Shoes",13:"Corn Beef",14:"132",15:"The White Pearl of India",16:"Smoking",17:"Red",18:"Rooster",19:"Mortal Kombat"], possibleAnswers: [0:["Sweden","U.S.A","France"],1:["The fear of using improper grammer","The fear of math and the use of numbers","The fear of glasses, mirrors and any refelctive surface"],2:["A backpack","A mug","Pack of cards"],3:["May","December","June"],4:["Blue Jays","Cardinals","Yankees"],5:["Strawberry, Caramel,Chocolate","Vanilla,Strawberry,Coffee","Chocolate,Strawberry,Mint"],6:["Hovels","Cultist","Seances"],7:["Starfire","Darkstar","Paladin"],8:["Poults","Toms","Chick"],9:["Stinky Drink","Fresh Water","Heroin"],10:["U.K","Canada","Spain"],11:["Cocoa#","Mud","Brew"],12:["Hats","Suits","Kilts"],13:["Roast Beef","Veal","Bacon"],14:["150","200","52"],15:["The Pride of India","The Symbol of India","The Icon of India"],16:["Vomiting","Bringing your own booze","Laughing"],17:["Orange","Green","Yellow"],18:["Albatross","Goose","Turkey"],19:["Mario Odyseey","Final Fantasy VIII","Call of Juarez"]], imageName: ""))
//    //MARK: Science Beginner
//    Quizzes.quizzes.append(Quizzes(title: "Science for noobs", description: "These are a little easier than the other science quizzes", questions: [0:"Where in your body would you find your Hippocampus?",1:"DNA carrys what type of molecule?",2:"The scientific chemical name for quicksilver is?",3:"The study of Fungi is called what?",4:"What is the common term for an injury to the neck caused by a jerk of the head?",5:"What is the only insect that can turn its head like humans?",6:"How many compartments does the cow's stomach have?",7:"Ketchup was sold in the 1830’s as what?",8:"The imperial fluid pint consists of how many imperial fluid ounces?",9:"What is the most common type of star in the universe?",10:"What percentage of a cucumber is water?",11:"What name is given to trees that lose their leaves annually?",12:"Momentum is calculated by?",13:"Whar is a rhino horn made of?",14:"How many pairs of wings does a Bee have?",15:"What celestial body orbits the Earth?",16:"Which direction does the Sun rise from?",17:"A group of lions is called a what?",18:"What do male lions do about 20 hours a day?",19:"What is the largest organ in the human body?"], answer: [0:"Brain",1:"Genetic",2:"Mercury",3:"Mycology",4:"Whiplash",5:"Praying Mantis",6:"Four",7:"Medicine",8:"20",9:"Red dwarf",10:"96",11:"Deciduous",12:"Mass multiplied by velocity",13:"Keratin",14:"2",15:"The Moon",16:"The East",17:"Pride",18:"Sleep",19:"Skin"], possibleAnswers: [0:["Feet","Hands","Legs"],1:["Carbon","Oxygen","Calcium"],2:["Silver","Adamantium","Aluminum"],3:["Micro Biology","Anthropology","Chemistry"],4:["Neck ache","Headache","Neck Kink"],5:["A Fly","Wasp","Ladybug"],6:["Five","Six","Three"],7:["Ointment","A Drink","A Condiment"],8:["30","12","22"],9:["Neutron Star","Supergiant Stars","White Dwarf Stars"],10:["88","59","30"],11:["Evergreen","Conifer","Coniferous"],12:["Speed divided by time","Time multipled by speed","Velocity multiplied by speed"],13:["Ivory","Bone","Calcium"],14:["1","4","3"],15:["The International Space Station","The Sun","Satellites"],16:["The West","The North","The South"],17:["Pack","Marshall","Flock"],18:["Procreate","Eat","Exercise"],19:["Brain","Heart","Lungs"]], imageName: ""))
//    //MARK: Science and Related
//    Quizzes.quizzes.append(Quizzes(title: "Science and related", description: "Not so easy questions on science and science related questions", questions: [0:"What is teh name of the ship Charles Darwin saild on when he made his historic voyage to the Galapagos Islands?",1:"Mark Twain is credited with the creation of what? Patented in the 19th century.",2:"The Cotton plant is attacked by what animal?",3:"The birds , Blue, Pinyon, and Steller's are all belong to what species of bird?",4:"Chickens were introduced to the New World by which famous explorer?",5:"What is a newley hatched fish called?",6:"What word describes one tenth of a nautical mile?",7:"A light aircraft that does not use an engine is called?",8:"Hydraulics is the study of?",9:"Another name for a beetle is?",10:"A Scientist who studies the atmospher and atmospheric changes is called a what?",11:"The first U.S  spacecraft to send back pictures of the moon was called?",12:"Who invented the Lie Detector (Polygraph)?",13:"Hysteria in females in the 16th and 17th century was still believed to be caused by the retention of fluids where?",14:"What instrument is used to measure the strength of a magnetic field?",15:"Who was the second man to set foot on the Moon?",16:"What do whales feed their young?",17:"How many seconds in 1 hour?",18:"What type of plant is a Saguaro",19:"What important sensory organ do earthworms lack?"], answer: [0:"H.M.S Beagle",1:"Adjustable Elastic Suspenders",2:"The Boll Weevil",3:"Jay",4:"Christopher Columbus",5:"Fry",6:"Cable",7:"Glider or Sailplane",8:"Fluids",9:"Weevil",10:"Meteorologist",11:"Rengar VII",12:"John Augustus Larson",13:"Uterus",14:"Magnetometer",15:"Buzz Aldrin",16:"Milk",17:"3600",18:"Cactus",19:"Eyes"], possibleAnswers: [0:["SS Iron Foot","The Guilded Lady","H.M.S Ywain"],1:["White out","The type writer","The first ink pen"],2:["Rats","Cats","Mole"],3:["Heron","Waterfowl","Crane"],4:["Marco Polo","Amerigo Vespucci","Francis Drake"],5:["Guppie","Minnow","Roe"],6:["Knot","Cord","Cap"],7:["A boat","A Hovercraft","A Cessna"],8:["Pressure","Mechanical Parts","Mechanical Movement"],9:["Cockroach","Anthropoda","Diptera"],10:["Anthropologist","Epidemiologist","Biologist"],11:["Mir","Discovery","Pathfinder"],12:["Lucas Wesley","Mike Masters","Damien Gerd"],13:["Anus","Nose","Lungs"],14:["Enertron","Magmeter","Force Guage"],15:["Chris Hadfield","Fred Haise","Neil Armstrong"],16:["Shrimp","Plankton","Seaweed"],17:["2200","4500","3000"],18:["Water Plant","A Perennial","Marijuana"],19:["Eyelids","Skin","Muscles"]], imageName: ""))
//    //MARK: Science Intermediate
//    Quizzes.quizzes.append(Quizzes(title: "Science Intermediate", description: "If you really know science this quiz is for you.", questions: [0:"Ladybugs survive hibernation by eating what?",1:"What element on the periodic table is given the symbol 'I'?",2:"What is the chemical symbol for Californium",3:"The herb Parsley, it's latin name is what?",4:"The duodenum, jejenum and ileum together all make up what?",5:"Plasma is the liquid component of what?",6:"The Bowman's capsules are located where?",7:"What is the study of the sun called?",8:"What is the only bone in the human body that does not connect with any other bone?",9:"The fresh water fish known as the Northern Pike has a Lating name of?",10:"Quartz is made up fo which two chemical elements?",11:"Another way to describe Tree Ring dating is?",12:"What is the Vitamin in Carrots that helps maintain the accuracy of your vision?",13:"A medical condition known as 'Disprosopus', literally translates to what?",14:"A Tornadoe often comes into contact with a particular kind of cloud called?",15:"A 'Long Ton' is exactly how many pounds?",16:"A 'Pulsar' emits what kind of radiation?",17:"Max Planck won the Nobel Prize for discovering what?",18:"What is the name for the sun's outer atmosphere?",19:"Which one of your toes is also known as your 'hallux'?"], answer: [0:"Stored fat",1:"Iodine",2:"Cf",3:"Petroselinum crispum",4:"Small intenstine",5:"Blood",6:"Kidneys",7:"Heliology",8:"Hyoid",9:"Esox Lucius",10:"Silicon and Oxygen",11:"Dendrochronology",12:"Vitamin A",13:"Two-Faced",14:"Cumulonimbus cloud",15:"2240",16:"Electromagnetic Radiation",17:"Energy Quanta",18:"The corona",19:"Big Toe"], possibleAnswers: [0:["Leaves","Bark","Larva"],1:["Ibuprofen","Iodic Acid","Iron Chromite"],2:["Ca","C","Cp"],3:["Ligustrum","Bulapathum","Ocimus"],4:["Large intenstine","Stomach lining","Your skin"],5:["Oxygen","Petroleum","Mercury"],6:["Lungs","Heart","Liver"],7:["Armenology","Crustaceology","Syndesmology"],8:["Carpals","Vomer Bone","Mandible"],9:["Cyprinidae","Cobitis","Barilius"],10:["Crystal and Alkaline","Sulfate and Ammonium","Nitrogen and Calcium"],11:["Carbon Dating","Radiocarbon Dating","Dating"],12:["Vitamin V","Vitamin E","Vitamin C"],13:["Twin-Attached","Two-Fingers","Two-Body"],14:["Altocumulus","Cirrus","Nimbostratus"],15:["1000","1200","2932"],16:["Alpha Radiation","Beta Radiation","Neutron Radiation"],17:["Neutrons","Penicillin","Thermal Energy"],18:["The Organe","Flare II","U-Zone"],19:["Pinky Toe","Long Toe","Ring Toe"]], imageName: ""))
//
//    //MARK: Geography and Related
//    Quizzes.quizzes.append(Quizzes(title: "Geography and Related", description: "This quiz is all about geography and goegraphy related questions.", questions: [0:"Vatican City and what other country have square flags?",1:"What beer shares its name with the river that runs through Amsterdam?",2:"Which four US states share a border with Mexico?",3:"Lesotho is landlocked by which African country?",4:"What is the capital of Louisiana?",5:"What color is the cross on the flag of Finlad?",6:"Which bird is the national bird of Greece?",7:"Lake Sakakawea is the largest lake in which US state?",8:"To which South American country to the Galapagos Islands belong?",9:"Which desert covers part of China and Mongolia?",10:"In what country is the Nobel Peace Prize awarded?",11:"What is the modern day equivalent of Formosa?",12:"Which US state is home to Crater Lake National Park?",13:"Which South American country's name is literally 'Land of Silver'?",14:"Candy canes are said to have originated from which European country?",15:"Alcatraz is located in which city?",16:"Independence Hall, home to the Liberty Bell, is located in which US state?",17:"Approximately, how many feet above the sea level is Machi Picchu?",18:"Which US state is nicknamed the 'Evergreen State'?",19:"Where is Mount Olympus?"], answer: [0:"Switzerland",1:"Amstel",2:"Arizona,California,New Mexico, Texas",3:"South Africa",4:"Baton Rouge",5:"Blue",6:"Little Owl",7:"North Dakota",8:"Ecuador",9:"Gobi",10:"Norway",11:"Taiwan",12:"Oregon",13:"Argentina",14:"Germany",15:"San Francisco",16:"Pennsylvania",17:"8000",18:"Washington",19:"Greece"], possibleAnswers: [0:["Italy","France","Germany"],1:["Nile","Zaan","Rideau"],2:["Florida,California,New Mexico and Texas","New York, California, Florida, Maine","Texas,Hawaii,California, New Mexico"],3:["Congo","Algeria","Ghana"],4:["Rikers","San Juan","Trenton"],5:["Orange","Green","White"],6:["Eagle","Pelican","Goose"],7:["South Dakota","California","Arizona"],8:["Ghana","Ethiopia","Cabo Verde"],9:["Sahara","Sonoran","Thar"],10:["Sweden","Switzerland","France"],11:["China","Malaysia","Vietnam"],12:["Texas","California","North Dakota"],13:["Mexico","Venezuela","Brazil"],14:["France","England","Spain"],15:["Los Angeles","San Diego","San Jose"],16:["Washington State","Maine","New York"],17:["6000","7000","5000"],18:["North Dakota","South Dakota","Maine"],19:["Spain","Italy","Austria"]], imageName: ""))
//
//    //MARK: Geography and Related
//    Quizzes.quizzes.append(Quizzes(title: "Geography and Related 2", description: "This quiz is all about geography and geography related questions.", questions: [0:"What tree appears on the national flag of Lebanon?",1:"What is the official language of Egypt?",2:"What body of water separates Australia and New Zealand?",3:"In which US state is Crater Lake found?",4:"What is Canberra's Telstra Tower also known as?",5:"What is the capital of India",6:"What is the fifth largest country in the world?",7:"What ocean separates North America from Europe?",8:"What is the capital of Botswana?",9:"What U.S city is nicknamed the 'Cradle of Aviation'?",10:"Yellowstone Lake is the largest naturally occurring lake in which state?",11:"It was illegal for women to wear what in 19th century Florence?",12:"What year did Cambodia gain its independence from France?",13:"Greece is part of which peninsula?",14:"The resort city of Aspen is located in which US state?",15:"What century did the Icelandic Vikings first reach the island of Newfoundland?",16:"Which US state has the least rainfall?",17:"What country lies on Israel’s northern border?",18:"In which country would you find the city Geneva?",19:"What is the longest river in the world?"], answer: [0:"Cedar Tree",1:"Arabic",2:"Tasman Sea",3:"Oregon",4:"Black Mountain Tower",5:"New Delhi",6:"Brazil",7:"Atlantic",8:"Gaborone",9:"Dayton, Ohio",10:"Wyoming",11:"Buttons",12:"1953",13:"Balkan",14:"Colorado",15:"11th Century",16:"Nevada",17:"Lebanon",18:"Switzerland",19:"The Nile"], possibleAnswers: [0:["Birch Tree","Pine Tree","Elm Tree"],1:["Hindi","Bangla/Bengali","Egyptian"],2:["Black Sea","Gulf of Carpentaria","Coral Sea"],3:["California","Texas","Ohio"],4:["The Tower","Hilltop Mountain Tower","Black's Tower"],5:["Patna","Mumbai","Thiruvananthapuram"],6:["Mexico","India","France"],7:["Pacific","Artic","Indian"],8:["Ramotswa","Mogoditshane","Mochudi"],9:["Portland, Maine","Adams, Tennessee","Philadelphia, Pennsylvania"],10:["California","Alaska","New Mexico"],11:["Pants","Bras","Jewlery"],12:["1966","1949","1959"],13:["Jutland","Iberian","Balkan"],14:["California","Washington","Maine"],15:["12th Century","10th Century","9th Century"],16:["California","New Mexico","Texas"],17:["Jordan","Syria","Saudi Arabia"],18:["Denmark","Finland","Sweden"],19:["The Amazon","The Mississippi","The Yangtze"]], imageName: ""))
//    
//    //MARK: Geography and Related
//    Quizzes.quizzes.append(Quizzes(title: "Geography and Related 3", description: "This quiz is all about geogrpahy and geogrpahy related questions.", questions: [0:"Which US state is called the Magnolia State?",1:"What is the largest city in India?",2:"Which US state is nicknamed 'Land of 10,000 Lakes'?",3:"What is Ethiopia's main commercial crop?",4:"In what country is Thunder Bay?",5:"What are Italy's two largest islands?",6:"Columbia is the capital of which US state?",7:"What US state's flag has different images on the front and back?",8:"On what continent is the Balkan Peninsula?",9:"What U.S. state is home to 'The Raisin Capital of the World'?",10:"What country borders Egypt to the west?",11:"In what country would you find the active volcano 'Lassen Peak'?",12:"What is the capital of El Salvador?",13:"What is the capital of Guam?",14:"What is the smallest country by area and population?",15:"What US National Park is known for its geysers?",16:"Captain Henry Morgan used what island as a base of buccaneer operations?",17:"Berlin stands on the banks of which river?",18:"What line on a map connects places of equal rainfall?",19:"In which European city would you find the Rijksmuseum?"], answer: [0:"Mississippi",1:"Mumbai",2:"Minnesota",3:"Coffee",4:"Canada",5:"Sicily and Sardinia",6:"South Carolina",7:"Oregon",8:"Eruope",9:"California",10:"Libya",11:"United States",12:"San Salvador",13:"Hagatna",14:"Vatican City",15:"Yellowstone National Park",16:"Jamaica",17:"Spree",18:"Isohyet",19:"Amsterdam"], possibleAnswers: [0:["Texas","Florida","Massachusetts"],1:["Chennai","Bengaluru","Kolkata"],2:["Colorado","Ohio","Pennsylvania"],3:["Tobacco","Corn","Agave"],4:["Britain","Germany","United States"],5:["Elba and Panarea","Capri and Stromboli","Ischia and Ponza"],6:["North Carolina","Minnesota","Wyoming"],7:["Arizona","Texas","New York"],8:["North America","South America","Asia"],9:["Florida","Texas","New Mexico"],10:["Syria","Lebanon","Jordan"],11:["Canada","Russia","Italy"],12:["Santa Ana","Santa Tecla","San Miguel"],13:["Santa Rita","Agat","Barrigada"],14:["Republic of Nauru","Principality of Liechtenstein","Tuvalu"],15:["Yosemite National Park","Glacier National Park","Zion National Park"],16:["Cuba","The Bahamas","Dominican Republic"],17:["Rhine River","Danube River","Elbe"],18:["Longitude","Latitude","Marginals Line"],19:["Berlin","Paris","Moscow"]], imageName: ""))
//    
//    //MARK: Entertainment / Pop Culture
//    Quizzes.quizzes.append(Quizzes(title: "Entertainment and Pop Culture", description: "This quiz will test your knowledge on Entertainment and Pop Culture. Good Luck!", questions: [0:"",1:"",2:"",3:"",4:"",5:"",6:"",7:"",8:"",9:"",10:"",11:"",12:"",13:"",14:"",15:"",16:"",17:"",18:"",19:""], answer: [0:"",1:"",2:"",3:"",4:"",5:"",6:"",7:"",8:"",9:"",10:"",11:"",12:"",13:"",14:"",15:"",16:"",17:"",18:"",19:""], possibleAnswers: [0:[""],1:[""],2:[""],3:[""],4:[""],5:[""],6:[""],7:[""],8:[""],9:[""],10:[""],11:[""],12:[""],13:[""],14:[""],15:[""],16:[""],17:[""],18:[""],19:[""]], imageName: ""))
//
//
//    
//    }


